# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headstation', '0003_auto_20171013_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
