# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headstation', '0004_auto_20171013_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='co2Reading',
            fields=[
                ('measurement_id', models.AutoField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('sensor_id', models.IntegerField()),
                ('co2', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HumidityReading',
            fields=[
                ('measurement_id', models.AutoField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('sensor_id', models.IntegerField()),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('measurement_id', models.AutoField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
